apiVersion: apps/v1
kind: Deployment
metadata:
  name: minion
  labels:
    app: minion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minion
  template:
    metadata:
      labels:
        app: minion
    spec:
      containers:
        - name: boss
          image: k8s-test/minion:1.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: minion
  labels:
    app: minion
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      name: http
      protocol: TCP
    - port: 5005
      targetPort: 5005
      name: debug
      protocol: TCP
  selector:
    app: minion