apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - image: byrnedo/alpine-curl
    name: curl
    ports:
    - containerPort: 8080
      protocol: TCP

  kubectl run -it curl --image=tutum/curl --rm --restart=Never -- bash